<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>WPF-UI.Abstractions</PackageId>
    <TargetFrameworks>net10.0;net9.0;net8.0;net481;net472;net462;netstandard2.1;netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Abstractions for the WPF UI.</Description>
    <CommonTags>$(CommonTags);abstractions;standard</CommonTags>
    <_SilenceIsAotCompatibleUnsupportedWarning>true</_SilenceIsAotCompatibleUnsupportedWarning>
  </PropertyGroup>

  <ItemGroup Condition="'$(GeneratePackageOnBuild)' == 'true'">
    <None Include="$(RepositoryDirectory)\src\Wpf.Ui.Abstractions\README.md" Pack="true" PackagePath="\README.md" Visible="False" />
  </ItemGroup>

  <!--项目构建完成后，将包推送到公司包管理器-->
  <Target Name="AutoPushNuGetPackage" AfterTargets="Pack" Condition="'$(Configuration)' == 'Debug'">
    <Exec Command="dotnet nuget push -s https://nuget.bciflex.com/v3/index.json --api-key GFteHZndtet8A1 --skip-duplicate $(PackageOutputPath)$(PackageId).$(Version).nupkg" />
  </Target>
</Project>
